### ISSUE TITLE
Create a Python Flask Cloud Foundry Application

### ISSUE THREAD

**Issue by savannahmccoy** [DevOps-Promo/promotions#34]
**As a** developer
**I need** to create a Python Flask Cloud Foundry application in IBM Cloud
**So that** the application registered and can be deployed.

**Assumptions:** 
*  The naming convention will use the singular version of the resource name prefixed by nyu- and suffixed by -service-s20 (i.e. promotion)

**Acceptance Criteria:**
```
Given python flask application has been created
When we attempt to deploy the project
Then it will successfully link to the cloud
```

**Comment by jc5808** [comment]
Hey Team - Per the Professor's note (included below), this story is actually related to the metadata files story. Once we get the pull request approved for the metadata files, I'll update this ticket.

"@John Caudle Actually the manifest.yml, runtime.txt, and Procfile are all part of that story because that's what makes a regular Flask application a Cloud Foundry compatable application."

**Comment by jc5808** [comment]
The Python Flask Cloud Foundry Application will be created the first time we run "ibmcloud cf push." 

@crb618 This is your story. I think we're in good shape on the dependencies and blockers. Can you run this and confirm?
