### ISSUE TITLE
Create UI Page

### ISSUE THREAD

**Issue by savannahmccoy** [DevOps-Promo/promotions#41]
**As a** Marketing Manager
**I need** a simple single UI page
**So that** I can easily interact with the resource backend

**Assumptions:** 
* There is not an existing UI page
* There is an example UI the development team can use as a reference
* The backend of the resource is fully implemented
* There is a cloud domain to deploy the resource/UI to

**Acceptance Criteria:**
```
Given the UI has been created
When I attempt to interact with the resource
Then I can successfully use the UI to perform actions
```

**Comment by jc5808** [comment]
Putting this back in done. Looks like the javascript isn't connected or working properly as the UI isn't ingesting any of the form fields I fill out. Doing some testing now, but any other ideas, reviews or tests are appreciated.

@savannahmccoy since you're more advanced here, would appreciate another set of eyes.
